Add check to see if active user is root in dependency install scripts

diff --git a/deps-compile b/deps-compile
--- a/deps-compile
+++ b/deps-compile
@@ -7,7 +7,11 @@ PACMAN_INSTALL=""
 PACMAN_PACKAGES=()
 PACMAN_POST=()
 
-if [ -f "/usr/bin/sudo" ]; then
+WHOIS=$(whoami)
+
+if [ "$WHOIS" == "root" ]; then
+	printf "\e[1;33mRunning as root user. If this is unintended, exit the script then exit the root shell or remove sudo/doas from your previous command.\e[0m\n"
+elif [ -f "/usr/bin/sudo" ]; then
 	DOAS_CMD="sudo"
 elif [ -f "/usr/bin/doas" ]; then
 	DOAS_CMD="doas"
@@ -31,9 +35,26 @@ elif [ -f "/usr/bin/pacman" ]; then
 	PACMAN_INSTALL="pacman -S"
 	PACMAN_PACKAGES=(base-devel extra-cmake-modules cmake kirigami2 kconfig ki18n kcoreaddons kde-sdk-meta gettext libgit2 meson)
 else
-	>&2 printf "\e[1;31mFailed to automatically detect your package manager\n\e[0m"
+	>&2 printf "\e[1;31mFailed to automatically detect your package manager, manual intervention is required\n\e[0m"
 	exit
 fi
+
+printf "\e[1;33mThe following packages will be installed: "
+echo "${PACMAN_PACKAGES[@]}"
+printf "Is this okay [y/n]?\e[0m "
+
+while true
+do
+	# shellcheck disable=SC2162
+	read OKAY
+
+	if [[ "$OKAY" == "N" || "$OKAY" == "n" ]]; then
+		printf "Exiting now...\n\e[0m"
+		exit 1
+	elif [[ "$OKAY" == "Y" || "$OKAY" == "y" ]]; then
+		break
+	fi
+done
 
 # Splitting is intentional, so I'm disabling this warning
 # shellcheck disable=SC2086
diff --git a/deps-runtime b/deps-runtime
--- a/deps-runtime
+++ b/deps-runtime
@@ -1,5 +1,5 @@
 #!/bin/bash
-echo "This script will install some required packages to compile Kirigami64 on Linux."
+echo "This script will install some required packages to use Kirigami64 on Linux."
 printf "This updated script should automatically detect your package manager for installing dependencies. \e[1;31mIf it doesn't, you will need to find the dependencies yourself.\e[0m\n"
 
 DOAS_CMD=""
@@ -7,7 +7,11 @@ PACMAN_INSTALL=""
 PACMAN_PACKAGES=()
 PACMAN_POST=()
 
-if [ -f "/usr/bin/sudo" ]; then
+WHOIS=$(whoami)
+
+if [ "$WHOIS" == "root" ]; then
+	printf "\e[1;33mRunning as root user. If this is unintended, exit the script then exit the root shell or remove sudo/doas from your previous command.\e[0m\n"
+elif [ -f "/usr/bin/sudo" ]; then
 	DOAS_CMD="sudo"
 elif [ -f "/usr/bin/doas" ]; then
 	DOAS_CMD="doas"
@@ -33,9 +37,26 @@ elif [ -f "/usr/bin/xbps-install" ]; then
 	PACMAN_INSTALL="xbps-install -S"
 	PACMAN_PACKAGES=(base-devel python3 SDL2-devel glew-devel)
 else
-	>&2 printf "\e[1;31mFailed to automatically detect your package manager\n\e[0m"
+	>&2 printf "\e[1;31mFailed to automatically detect your package manager, manual intervention is required\n\e[0m"
 	exit
 fi
+
+printf "\e[1;33mThe following packages will be installed: "
+echo "${PACMAN_PACKAGES[@]}"
+printf "Is this okay [y/n]?\e[0m "
+
+while true
+do
+	# shellcheck disable=SC2162
+	read OKAY
+
+	if [[ "$OKAY" == "N" || "$OKAY" == "n" ]]; then
+		printf "Exiting now...\n\e[0m"
+		exit 1
+	elif [[ "$OKAY" == "Y" || "$OKAY" == "y" ]]; then
+		break
+	fi
+done
 
 # Splitting is intentional, so I'm disabling this warning
 # shellcheck disable=SC2086
